
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import SimpleLayout from '@/components/layouts/SimpleLayout';
import { Modal, Button } from 'react-bootstrap';
import { useRouter } from 'next/router';
import React from 'react';


export default function Home() {
  const router = useRouter();
  

  const addGateway = () => {
    console.log('asd')
    router.push('/gateway/create');
  }
  return (
    <SimpleLayout title="Home">
        <div className={styles.container}>
      <Head>
        <title>Gateways-Peripherals</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <section>
  <h1>Hello, welcome to GATEWAYS-APP!</h1>
  <p>
    This is a simple app to manage Gateways and its Peripherals Devices, login (by github account) is required to edit data.
  </p>
  <p>
  <Link href='/gateway/list'>
              <a>Gateways</a>
            </Link><br/>
            <Link href='/peripheral/list'>
              <a>Peripherals</a>
            </Link>
  </p>
</section>
        
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
   
    </SimpleLayout>
    )
}
